return {
  'folke/which-key.nvim',

  config = function()
    local wk = require('which-key')

    wk.setup {
      plugins = {
        registers = false, -- breaks <C-r> in command line during macros
      },
    }

    wk.add({
      { "<leader>b",   group = "buffer" },
      { "<leader>c",   group = "creatures" },
      { "<leader>f",   group = "telescope" },
      { "<leader>g",   group = "git" },
      { "<leader>gb",  group = "buffer" },
      { "<leader>gbd", group = "diff" },
      { "<leader>gh",  group = "hunk" },
      { "<leader>gm",  desc = "line commit message" },
      { "<leader>gt",  group = "toggle" },
      { "<leader>gy",  group = "copy permalink" },
      { "<leader>h",   group = "highlight" },
      { "<leader>l",   group = "lsp" },
      { "<leader>lD",  group = "dump diagnostics" },
      { "<leader>lc",  group = "call graph" },
      { "<leader>ld",  group = "document" },
      { "<leader>lg",  group = "goto/query symbol" },
      { "<leader>lp",  group = "preview" },
      { "<leader>lq",  group = "quickfix" },
      { "<leader>lqc", group = "call graph" },
      { "<leader>lqd", group = "document" },
      { "<leader>lqg", group = "goto/query symbol" },
      { "<leader>lqw", group = "workspace" },
      { "<leader>lt",  group = "toggle" },
      { "<leader>lw",  group = "workspace" },
      { "<leader>lwf", group = "folders" },
      { "<leader>lx",  group = "server" },
      { "<leader>m",   group = "change directory" },
      { "<leader>t",   group = "toggles" },
      { "<leader>tc",  group = "colorcolumn" },
      { "<leader>ti",  group = "indent" },
      { "<leader>tn",  group = "line numbers" },
      { "<leader>w",   group = "wiki" },
      { "\\",          group = "visual-multi" },
      { "\\/",         desc = "regex search" },
      { "\\A",         desc = "select all" },
      { "\\\\",        desc = "add cursor" },
      { "cr",          group = "coerce" },
      { "cr-",         desc = "dash-case" },
      { "cr.",         desc = "dot.case" },
      { "cr<space>",   desc = "space case" },
      { "crU",         desc = "SNAKE_UPPERCASE" },
      { "cr_",         desc = "snake_case" },
      { "crc",         desc = "camelCase" },
      { "crk",         desc = "kebab-case" },
      { "crm",         desc = "MixedCase" },
      { "crs",         desc = "snake_case" },
      { "crt",         desc = "Title Case" },
      { "cru",         desc = "SNAKE_UPPERCASE" },
      { "cx",          group = "exchange" },
      { "cxc",         desc = "cancel exchange" },
      { "cxx",         desc = "exchange line" },
      { "g+",          desc = "later text state" },
      { "g-",          desc = "earlier text state" },
      { "gJ",          desc = "join construct" },
      { "gS",          desc = "split construct" },
      { "ga",          desc = "character info" },
      { "gb",          group = "block comment" },
      { "gbc",         desc = "end of line" },
      { "gc",          group = "line comment" },
      { "gcA",         desc = "append line comment" },
      { "gcO",         desc = "insert line comment above" },
      { "gcc",         desc = "current line" },
      { "gco",         desc = "insert line comment below" },
      { "yS",          group = "surround to line" },
      { "ySS",         desc = "current line" },
      { "ySs",         desc = "current line" },
      { "ys",          group = "surround" },
      { "yss",         desc = "current line" },
      {
        mode = { "x" },
        { "<leader>g",  group = "git" },
        { "<leader>gh", group = "hunk" },
        { "<leader>h",  group = "highlight" },
        { "S",          desc = "surround" },
        { "gS",         desc = "virtual surround (suppress indent)" },
        { "gb",         desc = "block comment" },
        { "gc",         desc = "line comment" },
      },
      {
        mode = { "o" },
        { "m",  desc = "treehopper" },
        { "gc", desc = "line comment" },
        { "gb", desc = "block comment" },
        { "cx", desc = "exchange" },
        { "ys", desc = "surround" },
        { "yS", desc = "surround to line" },
      },
    })
  end,
}
